// Code generated by ent, DO NOT EDIT.

package groupimagesizeaccount

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.GroupImageSizeAccount {
	return predicate.GroupImageSizeAccount(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.GroupImageSizeAccount {
	return predicate.GroupImageSizeAccount(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.GroupImageSizeAccount {
	return predicate.GroupImageSizeAccount(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.GroupImageSizeAccount {
	return predicate.GroupImageSizeAccount(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.GroupImageSizeAccount {
	return predicate.GroupImageSizeAccount(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.GroupImageSizeAccount {
	return predicate.GroupImageSizeAccount(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.GroupImageSizeAccount {
	return predicate.GroupImageSizeAccount(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.GroupImageSizeAccount {
	return predicate.GroupImageSizeAccount(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.GroupImageSizeAccount {
	return predicate.GroupImageSizeAccount(sql.FieldLTE(FieldID, id))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.GroupImageSizeAccount {
	return predicate.GroupImageSizeAccount(sql.FieldEQ(FieldGroupID, v))
}

// SizeTier applies equality check predicate on the "size_tier" field. It's identical to SizeTierEQ.
func SizeTier(v string) predicate.GroupImageSizeAccount {
	return predicate.GroupImageSizeAccount(sql.FieldEQ(FieldSizeTier, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.GroupImageSizeAccount {
	return predicate.GroupImageSizeAccount(sql.FieldEQ(FieldAccountID, v))
}

// Priority applies equality check predicate on the "priority" field. It's identical to PriorityEQ.
func Priority(v int) predicate.GroupImageSizeAccount {
	return predicate.GroupImageSizeAccount(sql.FieldEQ(FieldPriority, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.GroupImageSizeAccount {
	return predicate.GroupImageSizeAccount(sql.FieldEQ(FieldCreatedAt, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.GroupImageSizeAccount {
	return predicate.GroupImageSizeAccount(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.GroupImageSizeAccount {
	return predicate.GroupImageSizeAccount(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.GroupImageSizeAccount {
	return predicate.GroupImageSizeAccount(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.GroupImageSizeAccount {
	return predicate.GroupImageSizeAccount(sql.FieldNotIn(FieldGroupID, vs...))
}

// SizeTierEQ applies the EQ predicate on the "size_tier" field.
func SizeTierEQ(v string) predicate.GroupImageSizeAccount {
	return predicate.GroupImageSizeAccount(sql.FieldEQ(FieldSizeTier, v))
}

// SizeTierNEQ applies the NEQ predicate on the "size_tier" field.
func SizeTierNEQ(v string) predicate.GroupImageSizeAccount {
	return predicate.GroupImageSizeAccount(sql.FieldNEQ(FieldSizeTier, v))
}

// SizeTierIn applies the In predicate on the "size_tier" field.
func SizeTierIn(vs ...string) predicate.GroupImageSizeAccount {
	return predicate.GroupImageSizeAccount(sql.FieldIn(FieldSizeTier, vs...))
}

// SizeTierNotIn applies the NotIn predicate on the "size_tier" field.
func SizeTierNotIn(vs ...string) predicate.GroupImageSizeAccount {
	return predicate.GroupImageSizeAccount(sql.FieldNotIn(FieldSizeTier, vs...))
}

// SizeTierGT applies the GT predicate on the "size_tier" field.
func SizeTierGT(v string) predicate.GroupImageSizeAccount {
	return predicate.GroupImageSizeAccount(sql.FieldGT(FieldSizeTier, v))
}

// SizeTierGTE applies the GTE predicate on the "size_tier" field.
func SizeTierGTE(v string) predicate.GroupImageSizeAccount {
	return predicate.GroupImageSizeAccount(sql.FieldGTE(FieldSizeTier, v))
}

// SizeTierLT applies the LT predicate on the "size_tier" field.
func SizeTierLT(v string) predicate.GroupImageSizeAccount {
	return predicate.GroupImageSizeAccount(sql.FieldLT(FieldSizeTier, v))
}

// SizeTierLTE applies the LTE predicate on the "size_tier" field.
func SizeTierLTE(v string) predicate.GroupImageSizeAccount {
	return predicate.GroupImageSizeAccount(sql.FieldLTE(FieldSizeTier, v))
}

// SizeTierContains applies the Contains predicate on the "size_tier" field.
func SizeTierContains(v string) predicate.GroupImageSizeAccount {
	return predicate.GroupImageSizeAccount(sql.FieldContains(FieldSizeTier, v))
}

// SizeTierHasPrefix applies the HasPrefix predicate on the "size_tier" field.
func SizeTierHasPrefix(v string) predicate.GroupImageSizeAccount {
	return predicate.GroupImageSizeAccount(sql.FieldHasPrefix(FieldSizeTier, v))
}

// SizeTierHasSuffix applies the HasSuffix predicate on the "size_tier" field.
func SizeTierHasSuffix(v string) predicate.GroupImageSizeAccount {
	return predicate.GroupImageSizeAccount(sql.FieldHasSuffix(FieldSizeTier, v))
}

// SizeTierEqualFold applies the EqualFold predicate on the "size_tier" field.
func SizeTierEqualFold(v string) predicate.GroupImageSizeAccount {
	return predicate.GroupImageSizeAccount(sql.FieldEqualFold(FieldSizeTier, v))
}

// SizeTierContainsFold applies the ContainsFold predicate on the "size_tier" field.
func SizeTierContainsFold(v string) predicate.GroupImageSizeAccount {
	return predicate.GroupImageSizeAccount(sql.FieldContainsFold(FieldSizeTier, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.GroupImageSizeAccount {
	return predicate.GroupImageSizeAccount(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.GroupImageSizeAccount {
	return predicate.GroupImageSizeAccount(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.GroupImageSizeAccount {
	return predicate.GroupImageSizeAccount(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.GroupImageSizeAccount {
	return predicate.GroupImageSizeAccount(sql.FieldNotIn(FieldAccountID, vs...))
}

// PriorityEQ applies the EQ predicate on the "priority" field.
func PriorityEQ(v int) predicate.GroupImageSizeAccount {
	return predicate.GroupImageSizeAccount(sql.FieldEQ(FieldPriority, v))
}

// PriorityNEQ applies the NEQ predicate on the "priority" field.
func PriorityNEQ(v int) predicate.GroupImageSizeAccount {
	return predicate.GroupImageSizeAccount(sql.FieldNEQ(FieldPriority, v))
}

// PriorityIn applies the In predicate on the "priority" field.
func PriorityIn(vs ...int) predicate.GroupImageSizeAccount {
	return predicate.GroupImageSizeAccount(sql.FieldIn(FieldPriority, vs...))
}

// PriorityNotIn applies the NotIn predicate on the "priority" field.
func PriorityNotIn(vs ...int) predicate.GroupImageSizeAccount {
	return predicate.GroupImageSizeAccount(sql.FieldNotIn(FieldPriority, vs...))
}

// PriorityGT applies the GT predicate on the "priority" field.
func PriorityGT(v int) predicate.GroupImageSizeAccount {
	return predicate.GroupImageSizeAccount(sql.FieldGT(FieldPriority, v))
}

// PriorityGTE applies the GTE predicate on the "priority" field.
func PriorityGTE(v int) predicate.GroupImageSizeAccount {
	return predicate.GroupImageSizeAccount(sql.FieldGTE(FieldPriority, v))
}

// PriorityLT applies the LT predicate on the "priority" field.
func PriorityLT(v int) predicate.GroupImageSizeAccount {
	return predicate.GroupImageSizeAccount(sql.FieldLT(FieldPriority, v))
}

// PriorityLTE applies the LTE predicate on the "priority" field.
func PriorityLTE(v int) predicate.GroupImageSizeAccount {
	return predicate.GroupImageSizeAccount(sql.FieldLTE(FieldPriority, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.GroupImageSizeAccount {
	return predicate.GroupImageSizeAccount(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.GroupImageSizeAccount {
	return predicate.GroupImageSizeAccount(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.GroupImageSizeAccount {
	return predicate.GroupImageSizeAccount(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.GroupImageSizeAccount {
	return predicate.GroupImageSizeAccount(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.GroupImageSizeAccount {
	return predicate.GroupImageSizeAccount(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.GroupImageSizeAccount {
	return predicate.GroupImageSizeAccount(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.GroupImageSizeAccount {
	return predicate.GroupImageSizeAccount(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.GroupImageSizeAccount {
	return predicate.GroupImageSizeAccount(sql.FieldLTE(FieldCreatedAt, v))
}

// HasAccount applies the HasEdge predicate on the "account" edge.
func HasAccount() predicate.GroupImageSizeAccount {
	return predicate.GroupImageSizeAccount(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, AccountTable, AccountColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountWith applies the HasEdge predicate on the "account" edge with a given conditions (other predicates).
func HasAccountWith(preds ...predicate.Account) predicate.GroupImageSizeAccount {
	return predicate.GroupImageSizeAccount(func(s *sql.Selector) {
		step := newAccountStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.GroupImageSizeAccount {
	return predicate.GroupImageSizeAccount(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.Group) predicate.GroupImageSizeAccount {
	return predicate.GroupImageSizeAccount(func(s *sql.Selector) {
		step := newGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GroupImageSizeAccount) predicate.GroupImageSizeAccount {
	return predicate.GroupImageSizeAccount(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GroupImageSizeAccount) predicate.GroupImageSizeAccount {
	return predicate.GroupImageSizeAccount(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GroupImageSizeAccount) predicate.GroupImageSizeAccount {
	return predicate.GroupImageSizeAccount(sql.NotPredicates(p))
}
