// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/groupimagesizeaccount"
)

// GroupImageSizeAccountCreate is the builder for creating a GroupImageSizeAccount entity.
type GroupImageSizeAccountCreate struct {
	config
	mutation *GroupImageSizeAccountMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetGroupID sets the "group_id" field.
func (_c *GroupImageSizeAccountCreate) SetGroupID(v int64) *GroupImageSizeAccountCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetSizeTier sets the "size_tier" field.
func (_c *GroupImageSizeAccountCreate) SetSizeTier(v string) *GroupImageSizeAccountCreate {
	_c.mutation.SetSizeTier(v)
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *GroupImageSizeAccountCreate) SetAccountID(v int64) *GroupImageSizeAccountCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetPriority sets the "priority" field.
func (_c *GroupImageSizeAccountCreate) SetPriority(v int) *GroupImageSizeAccountCreate {
	_c.mutation.SetPriority(v)
	return _c
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_c *GroupImageSizeAccountCreate) SetNillablePriority(v *int) *GroupImageSizeAccountCreate {
	if v != nil {
		_c.SetPriority(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *GroupImageSizeAccountCreate) SetCreatedAt(v time.Time) *GroupImageSizeAccountCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *GroupImageSizeAccountCreate) SetNillableCreatedAt(v *time.Time) *GroupImageSizeAccountCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetAccount sets the "account" edge to the Account entity.
func (_c *GroupImageSizeAccountCreate) SetAccount(v *Account) *GroupImageSizeAccountCreate {
	return _c.SetAccountID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *GroupImageSizeAccountCreate) SetGroup(v *Group) *GroupImageSizeAccountCreate {
	return _c.SetGroupID(v.ID)
}

// Mutation returns the GroupImageSizeAccountMutation object of the builder.
func (_c *GroupImageSizeAccountCreate) Mutation() *GroupImageSizeAccountMutation {
	return _c.mutation
}

// Save creates the GroupImageSizeAccount in the database.
func (_c *GroupImageSizeAccountCreate) Save(ctx context.Context) (*GroupImageSizeAccount, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GroupImageSizeAccountCreate) SaveX(ctx context.Context) *GroupImageSizeAccount {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GroupImageSizeAccountCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GroupImageSizeAccountCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GroupImageSizeAccountCreate) defaults() {
	if _, ok := _c.mutation.Priority(); !ok {
		v := groupimagesizeaccount.DefaultPriority
		_c.mutation.SetPriority(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := groupimagesizeaccount.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GroupImageSizeAccountCreate) check() error {
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "GroupImageSizeAccount.group_id"`)}
	}
	if _, ok := _c.mutation.SizeTier(); !ok {
		return &ValidationError{Name: "size_tier", err: errors.New(`ent: missing required field "GroupImageSizeAccount.size_tier"`)}
	}
	if v, ok := _c.mutation.SizeTier(); ok {
		if err := groupimagesizeaccount.SizeTierValidator(v); err != nil {
			return &ValidationError{Name: "size_tier", err: fmt.Errorf(`ent: validator failed for field "GroupImageSizeAccount.size_tier": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "GroupImageSizeAccount.account_id"`)}
	}
	if _, ok := _c.mutation.Priority(); !ok {
		return &ValidationError{Name: "priority", err: errors.New(`ent: missing required field "GroupImageSizeAccount.priority"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "GroupImageSizeAccount.created_at"`)}
	}
	if len(_c.mutation.AccountIDs()) == 0 {
		return &ValidationError{Name: "account", err: errors.New(`ent: missing required edge "GroupImageSizeAccount.account"`)}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "GroupImageSizeAccount.group"`)}
	}
	return nil
}

func (_c *GroupImageSizeAccountCreate) sqlSave(ctx context.Context) (*GroupImageSizeAccount, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GroupImageSizeAccountCreate) createSpec() (*GroupImageSizeAccount, *sqlgraph.CreateSpec) {
	var (
		_node = &GroupImageSizeAccount{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(groupimagesizeaccount.Table, sqlgraph.NewFieldSpec(groupimagesizeaccount.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.SizeTier(); ok {
		_spec.SetField(groupimagesizeaccount.FieldSizeTier, field.TypeString, value)
		_node.SizeTier = value
	}
	if value, ok := _c.mutation.Priority(); ok {
		_spec.SetField(groupimagesizeaccount.FieldPriority, field.TypeInt, value)
		_node.Priority = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(groupimagesizeaccount.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   groupimagesizeaccount.AccountTable,
			Columns: []string{groupimagesizeaccount.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AccountID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   groupimagesizeaccount.GroupTable,
			Columns: []string{groupimagesizeaccount.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GroupImageSizeAccount.Create().
//		SetGroupID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GroupImageSizeAccountUpsert) {
//			SetGroupID(v+v).
//		}).
//		Exec(ctx)
func (_c *GroupImageSizeAccountCreate) OnConflict(opts ...sql.ConflictOption) *GroupImageSizeAccountUpsertOne {
	_c.conflict = opts
	return &GroupImageSizeAccountUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GroupImageSizeAccount.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GroupImageSizeAccountCreate) OnConflictColumns(columns ...string) *GroupImageSizeAccountUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GroupImageSizeAccountUpsertOne{
		create: _c,
	}
}

type (
	// GroupImageSizeAccountUpsertOne is the builder for "upsert"-ing
	//  one GroupImageSizeAccount node.
	GroupImageSizeAccountUpsertOne struct {
		create *GroupImageSizeAccountCreate
	}

	// GroupImageSizeAccountUpsert is the "OnConflict" setter.
	GroupImageSizeAccountUpsert struct {
		*sql.UpdateSet
	}
)

// SetGroupID sets the "group_id" field.
func (u *GroupImageSizeAccountUpsert) SetGroupID(v int64) *GroupImageSizeAccountUpsert {
	u.Set(groupimagesizeaccount.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *GroupImageSizeAccountUpsert) UpdateGroupID() *GroupImageSizeAccountUpsert {
	u.SetExcluded(groupimagesizeaccount.FieldGroupID)
	return u
}

// SetSizeTier sets the "size_tier" field.
func (u *GroupImageSizeAccountUpsert) SetSizeTier(v string) *GroupImageSizeAccountUpsert {
	u.Set(groupimagesizeaccount.FieldSizeTier, v)
	return u
}

// UpdateSizeTier sets the "size_tier" field to the value that was provided on create.
func (u *GroupImageSizeAccountUpsert) UpdateSizeTier() *GroupImageSizeAccountUpsert {
	u.SetExcluded(groupimagesizeaccount.FieldSizeTier)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *GroupImageSizeAccountUpsert) SetAccountID(v int64) *GroupImageSizeAccountUpsert {
	u.Set(groupimagesizeaccount.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *GroupImageSizeAccountUpsert) UpdateAccountID() *GroupImageSizeAccountUpsert {
	u.SetExcluded(groupimagesizeaccount.FieldAccountID)
	return u
}

// SetPriority sets the "priority" field.
func (u *GroupImageSizeAccountUpsert) SetPriority(v int) *GroupImageSizeAccountUpsert {
	u.Set(groupimagesizeaccount.FieldPriority, v)
	return u
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *GroupImageSizeAccountUpsert) UpdatePriority() *GroupImageSizeAccountUpsert {
	u.SetExcluded(groupimagesizeaccount.FieldPriority)
	return u
}

// AddPriority adds v to the "priority" field.
func (u *GroupImageSizeAccountUpsert) AddPriority(v int) *GroupImageSizeAccountUpsert {
	u.Add(groupimagesizeaccount.FieldPriority, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.GroupImageSizeAccount.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *GroupImageSizeAccountUpsertOne) UpdateNewValues() *GroupImageSizeAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(groupimagesizeaccount.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GroupImageSizeAccount.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *GroupImageSizeAccountUpsertOne) Ignore() *GroupImageSizeAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GroupImageSizeAccountUpsertOne) DoNothing() *GroupImageSizeAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GroupImageSizeAccountCreate.OnConflict
// documentation for more info.
func (u *GroupImageSizeAccountUpsertOne) Update(set func(*GroupImageSizeAccountUpsert)) *GroupImageSizeAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GroupImageSizeAccountUpsert{UpdateSet: update})
	}))
	return u
}

// SetGroupID sets the "group_id" field.
func (u *GroupImageSizeAccountUpsertOne) SetGroupID(v int64) *GroupImageSizeAccountUpsertOne {
	return u.Update(func(s *GroupImageSizeAccountUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *GroupImageSizeAccountUpsertOne) UpdateGroupID() *GroupImageSizeAccountUpsertOne {
	return u.Update(func(s *GroupImageSizeAccountUpsert) {
		s.UpdateGroupID()
	})
}

// SetSizeTier sets the "size_tier" field.
func (u *GroupImageSizeAccountUpsertOne) SetSizeTier(v string) *GroupImageSizeAccountUpsertOne {
	return u.Update(func(s *GroupImageSizeAccountUpsert) {
		s.SetSizeTier(v)
	})
}

// UpdateSizeTier sets the "size_tier" field to the value that was provided on create.
func (u *GroupImageSizeAccountUpsertOne) UpdateSizeTier() *GroupImageSizeAccountUpsertOne {
	return u.Update(func(s *GroupImageSizeAccountUpsert) {
		s.UpdateSizeTier()
	})
}

// SetAccountID sets the "account_id" field.
func (u *GroupImageSizeAccountUpsertOne) SetAccountID(v int64) *GroupImageSizeAccountUpsertOne {
	return u.Update(func(s *GroupImageSizeAccountUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *GroupImageSizeAccountUpsertOne) UpdateAccountID() *GroupImageSizeAccountUpsertOne {
	return u.Update(func(s *GroupImageSizeAccountUpsert) {
		s.UpdateAccountID()
	})
}

// SetPriority sets the "priority" field.
func (u *GroupImageSizeAccountUpsertOne) SetPriority(v int) *GroupImageSizeAccountUpsertOne {
	return u.Update(func(s *GroupImageSizeAccountUpsert) {
		s.SetPriority(v)
	})
}

// AddPriority adds v to the "priority" field.
func (u *GroupImageSizeAccountUpsertOne) AddPriority(v int) *GroupImageSizeAccountUpsertOne {
	return u.Update(func(s *GroupImageSizeAccountUpsert) {
		s.AddPriority(v)
	})
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *GroupImageSizeAccountUpsertOne) UpdatePriority() *GroupImageSizeAccountUpsertOne {
	return u.Update(func(s *GroupImageSizeAccountUpsert) {
		s.UpdatePriority()
	})
}

// Exec executes the query.
func (u *GroupImageSizeAccountUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GroupImageSizeAccountCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GroupImageSizeAccountUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *GroupImageSizeAccountUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *GroupImageSizeAccountUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// GroupImageSizeAccountCreateBulk is the builder for creating many GroupImageSizeAccount entities in bulk.
type GroupImageSizeAccountCreateBulk struct {
	config
	err      error
	builders []*GroupImageSizeAccountCreate
	conflict []sql.ConflictOption
}

// Save creates the GroupImageSizeAccount entities in the database.
func (_c *GroupImageSizeAccountCreateBulk) Save(ctx context.Context) ([]*GroupImageSizeAccount, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*GroupImageSizeAccount, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GroupImageSizeAccountMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GroupImageSizeAccountCreateBulk) SaveX(ctx context.Context) []*GroupImageSizeAccount {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GroupImageSizeAccountCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GroupImageSizeAccountCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GroupImageSizeAccount.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GroupImageSizeAccountUpsert) {
//			SetGroupID(v+v).
//		}).
//		Exec(ctx)
func (_c *GroupImageSizeAccountCreateBulk) OnConflict(opts ...sql.ConflictOption) *GroupImageSizeAccountUpsertBulk {
	_c.conflict = opts
	return &GroupImageSizeAccountUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GroupImageSizeAccount.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GroupImageSizeAccountCreateBulk) OnConflictColumns(columns ...string) *GroupImageSizeAccountUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GroupImageSizeAccountUpsertBulk{
		create: _c,
	}
}

// GroupImageSizeAccountUpsertBulk is the builder for "upsert"-ing
// a bulk of GroupImageSizeAccount nodes.
type GroupImageSizeAccountUpsertBulk struct {
	create *GroupImageSizeAccountCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.GroupImageSizeAccount.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *GroupImageSizeAccountUpsertBulk) UpdateNewValues() *GroupImageSizeAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(groupimagesizeaccount.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GroupImageSizeAccount.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *GroupImageSizeAccountUpsertBulk) Ignore() *GroupImageSizeAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GroupImageSizeAccountUpsertBulk) DoNothing() *GroupImageSizeAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GroupImageSizeAccountCreateBulk.OnConflict
// documentation for more info.
func (u *GroupImageSizeAccountUpsertBulk) Update(set func(*GroupImageSizeAccountUpsert)) *GroupImageSizeAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GroupImageSizeAccountUpsert{UpdateSet: update})
	}))
	return u
}

// SetGroupID sets the "group_id" field.
func (u *GroupImageSizeAccountUpsertBulk) SetGroupID(v int64) *GroupImageSizeAccountUpsertBulk {
	return u.Update(func(s *GroupImageSizeAccountUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *GroupImageSizeAccountUpsertBulk) UpdateGroupID() *GroupImageSizeAccountUpsertBulk {
	return u.Update(func(s *GroupImageSizeAccountUpsert) {
		s.UpdateGroupID()
	})
}

// SetSizeTier sets the "size_tier" field.
func (u *GroupImageSizeAccountUpsertBulk) SetSizeTier(v string) *GroupImageSizeAccountUpsertBulk {
	return u.Update(func(s *GroupImageSizeAccountUpsert) {
		s.SetSizeTier(v)
	})
}

// UpdateSizeTier sets the "size_tier" field to the value that was provided on create.
func (u *GroupImageSizeAccountUpsertBulk) UpdateSizeTier() *GroupImageSizeAccountUpsertBulk {
	return u.Update(func(s *GroupImageSizeAccountUpsert) {
		s.UpdateSizeTier()
	})
}

// SetAccountID sets the "account_id" field.
func (u *GroupImageSizeAccountUpsertBulk) SetAccountID(v int64) *GroupImageSizeAccountUpsertBulk {
	return u.Update(func(s *GroupImageSizeAccountUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *GroupImageSizeAccountUpsertBulk) UpdateAccountID() *GroupImageSizeAccountUpsertBulk {
	return u.Update(func(s *GroupImageSizeAccountUpsert) {
		s.UpdateAccountID()
	})
}

// SetPriority sets the "priority" field.
func (u *GroupImageSizeAccountUpsertBulk) SetPriority(v int) *GroupImageSizeAccountUpsertBulk {
	return u.Update(func(s *GroupImageSizeAccountUpsert) {
		s.SetPriority(v)
	})
}

// AddPriority adds v to the "priority" field.
func (u *GroupImageSizeAccountUpsertBulk) AddPriority(v int) *GroupImageSizeAccountUpsertBulk {
	return u.Update(func(s *GroupImageSizeAccountUpsert) {
		s.AddPriority(v)
	})
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *GroupImageSizeAccountUpsertBulk) UpdatePriority() *GroupImageSizeAccountUpsertBulk {
	return u.Update(func(s *GroupImageSizeAccountUpsert) {
		s.UpdatePriority()
	})
}

// Exec executes the query.
func (u *GroupImageSizeAccountUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the GroupImageSizeAccountCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GroupImageSizeAccountCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GroupImageSizeAccountUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
