// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/groupimagesizeaccount"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// GroupImageSizeAccountUpdate is the builder for updating GroupImageSizeAccount entities.
type GroupImageSizeAccountUpdate struct {
	config
	hooks    []Hook
	mutation *GroupImageSizeAccountMutation
}

// Where appends a list predicates to the GroupImageSizeAccountUpdate builder.
func (_u *GroupImageSizeAccountUpdate) Where(ps ...predicate.GroupImageSizeAccount) *GroupImageSizeAccountUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *GroupImageSizeAccountUpdate) SetGroupID(v int64) *GroupImageSizeAccountUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *GroupImageSizeAccountUpdate) SetNillableGroupID(v *int64) *GroupImageSizeAccountUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetSizeTier sets the "size_tier" field.
func (_u *GroupImageSizeAccountUpdate) SetSizeTier(v string) *GroupImageSizeAccountUpdate {
	_u.mutation.SetSizeTier(v)
	return _u
}

// SetNillableSizeTier sets the "size_tier" field if the given value is not nil.
func (_u *GroupImageSizeAccountUpdate) SetNillableSizeTier(v *string) *GroupImageSizeAccountUpdate {
	if v != nil {
		_u.SetSizeTier(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *GroupImageSizeAccountUpdate) SetAccountID(v int64) *GroupImageSizeAccountUpdate {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *GroupImageSizeAccountUpdate) SetNillableAccountID(v *int64) *GroupImageSizeAccountUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *GroupImageSizeAccountUpdate) SetPriority(v int) *GroupImageSizeAccountUpdate {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *GroupImageSizeAccountUpdate) SetNillablePriority(v *int) *GroupImageSizeAccountUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *GroupImageSizeAccountUpdate) AddPriority(v int) *GroupImageSizeAccountUpdate {
	_u.mutation.AddPriority(v)
	return _u
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *GroupImageSizeAccountUpdate) SetAccount(v *Account) *GroupImageSizeAccountUpdate {
	return _u.SetAccountID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *GroupImageSizeAccountUpdate) SetGroup(v *Group) *GroupImageSizeAccountUpdate {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the GroupImageSizeAccountMutation object of the builder.
func (_u *GroupImageSizeAccountUpdate) Mutation() *GroupImageSizeAccountMutation {
	return _u.mutation
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *GroupImageSizeAccountUpdate) ClearAccount() *GroupImageSizeAccountUpdate {
	_u.mutation.ClearAccount()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *GroupImageSizeAccountUpdate) ClearGroup() *GroupImageSizeAccountUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GroupImageSizeAccountUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GroupImageSizeAccountUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GroupImageSizeAccountUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GroupImageSizeAccountUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GroupImageSizeAccountUpdate) check() error {
	if v, ok := _u.mutation.SizeTier(); ok {
		if err := groupimagesizeaccount.SizeTierValidator(v); err != nil {
			return &ValidationError{Name: "size_tier", err: fmt.Errorf(`ent: validator failed for field "GroupImageSizeAccount.size_tier": %w`, err)}
		}
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "GroupImageSizeAccount.account"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "GroupImageSizeAccount.group"`)
	}
	return nil
}

func (_u *GroupImageSizeAccountUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(groupimagesizeaccount.Table, groupimagesizeaccount.Columns, sqlgraph.NewFieldSpec(groupimagesizeaccount.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SizeTier(); ok {
		_spec.SetField(groupimagesizeaccount.FieldSizeTier, field.TypeString, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(groupimagesizeaccount.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(groupimagesizeaccount.FieldPriority, field.TypeInt, value)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   groupimagesizeaccount.AccountTable,
			Columns: []string{groupimagesizeaccount.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   groupimagesizeaccount.AccountTable,
			Columns: []string{groupimagesizeaccount.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   groupimagesizeaccount.GroupTable,
			Columns: []string{groupimagesizeaccount.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   groupimagesizeaccount.GroupTable,
			Columns: []string{groupimagesizeaccount.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{groupimagesizeaccount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GroupImageSizeAccountUpdateOne is the builder for updating a single GroupImageSizeAccount entity.
type GroupImageSizeAccountUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GroupImageSizeAccountMutation
}

// SetGroupID sets the "group_id" field.
func (_u *GroupImageSizeAccountUpdateOne) SetGroupID(v int64) *GroupImageSizeAccountUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *GroupImageSizeAccountUpdateOne) SetNillableGroupID(v *int64) *GroupImageSizeAccountUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetSizeTier sets the "size_tier" field.
func (_u *GroupImageSizeAccountUpdateOne) SetSizeTier(v string) *GroupImageSizeAccountUpdateOne {
	_u.mutation.SetSizeTier(v)
	return _u
}

// SetNillableSizeTier sets the "size_tier" field if the given value is not nil.
func (_u *GroupImageSizeAccountUpdateOne) SetNillableSizeTier(v *string) *GroupImageSizeAccountUpdateOne {
	if v != nil {
		_u.SetSizeTier(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *GroupImageSizeAccountUpdateOne) SetAccountID(v int64) *GroupImageSizeAccountUpdateOne {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *GroupImageSizeAccountUpdateOne) SetNillableAccountID(v *int64) *GroupImageSizeAccountUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *GroupImageSizeAccountUpdateOne) SetPriority(v int) *GroupImageSizeAccountUpdateOne {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *GroupImageSizeAccountUpdateOne) SetNillablePriority(v *int) *GroupImageSizeAccountUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *GroupImageSizeAccountUpdateOne) AddPriority(v int) *GroupImageSizeAccountUpdateOne {
	_u.mutation.AddPriority(v)
	return _u
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *GroupImageSizeAccountUpdateOne) SetAccount(v *Account) *GroupImageSizeAccountUpdateOne {
	return _u.SetAccountID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *GroupImageSizeAccountUpdateOne) SetGroup(v *Group) *GroupImageSizeAccountUpdateOne {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the GroupImageSizeAccountMutation object of the builder.
func (_u *GroupImageSizeAccountUpdateOne) Mutation() *GroupImageSizeAccountMutation {
	return _u.mutation
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *GroupImageSizeAccountUpdateOne) ClearAccount() *GroupImageSizeAccountUpdateOne {
	_u.mutation.ClearAccount()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *GroupImageSizeAccountUpdateOne) ClearGroup() *GroupImageSizeAccountUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// Where appends a list predicates to the GroupImageSizeAccountUpdate builder.
func (_u *GroupImageSizeAccountUpdateOne) Where(ps ...predicate.GroupImageSizeAccount) *GroupImageSizeAccountUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GroupImageSizeAccountUpdateOne) Select(field string, fields ...string) *GroupImageSizeAccountUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated GroupImageSizeAccount entity.
func (_u *GroupImageSizeAccountUpdateOne) Save(ctx context.Context) (*GroupImageSizeAccount, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GroupImageSizeAccountUpdateOne) SaveX(ctx context.Context) *GroupImageSizeAccount {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GroupImageSizeAccountUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GroupImageSizeAccountUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GroupImageSizeAccountUpdateOne) check() error {
	if v, ok := _u.mutation.SizeTier(); ok {
		if err := groupimagesizeaccount.SizeTierValidator(v); err != nil {
			return &ValidationError{Name: "size_tier", err: fmt.Errorf(`ent: validator failed for field "GroupImageSizeAccount.size_tier": %w`, err)}
		}
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "GroupImageSizeAccount.account"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "GroupImageSizeAccount.group"`)
	}
	return nil
}

func (_u *GroupImageSizeAccountUpdateOne) sqlSave(ctx context.Context) (_node *GroupImageSizeAccount, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(groupimagesizeaccount.Table, groupimagesizeaccount.Columns, sqlgraph.NewFieldSpec(groupimagesizeaccount.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "GroupImageSizeAccount.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, groupimagesizeaccount.FieldID)
		for _, f := range fields {
			if !groupimagesizeaccount.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != groupimagesizeaccount.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SizeTier(); ok {
		_spec.SetField(groupimagesizeaccount.FieldSizeTier, field.TypeString, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(groupimagesizeaccount.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(groupimagesizeaccount.FieldPriority, field.TypeInt, value)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   groupimagesizeaccount.AccountTable,
			Columns: []string{groupimagesizeaccount.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   groupimagesizeaccount.AccountTable,
			Columns: []string{groupimagesizeaccount.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   groupimagesizeaccount.GroupTable,
			Columns: []string{groupimagesizeaccount.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   groupimagesizeaccount.GroupTable,
			Columns: []string{groupimagesizeaccount.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &GroupImageSizeAccount{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{groupimagesizeaccount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
