// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/groupimagesizeaccount"
)

// GroupImageSizeAccount is the model entity for the GroupImageSizeAccount schema.
type GroupImageSizeAccount struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID int64 `json:"group_id,omitempty"`
	// Image billing tier: 1K, 2K, or 4K
	SizeTier string `json:"size_tier,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int64 `json:"account_id,omitempty"`
	// Lower values are scheduled first within the size tier pool
	Priority int `json:"priority,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the GroupImageSizeAccountQuery when eager-loading is set.
	Edges        GroupImageSizeAccountEdges `json:"edges"`
	selectValues sql.SelectValues
}

// GroupImageSizeAccountEdges holds the relations/edges for other nodes in the graph.
type GroupImageSizeAccountEdges struct {
	// Account holds the value of the account edge.
	Account *Account `json:"account,omitempty"`
	// Group holds the value of the group edge.
	Group *Group `json:"group,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// AccountOrErr returns the Account value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GroupImageSizeAccountEdges) AccountOrErr() (*Account, error) {
	if e.Account != nil {
		return e.Account, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: account.Label}
	}
	return nil, &NotLoadedError{edge: "account"}
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GroupImageSizeAccountEdges) GroupOrErr() (*Group, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*GroupImageSizeAccount) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case groupimagesizeaccount.FieldID, groupimagesizeaccount.FieldGroupID, groupimagesizeaccount.FieldAccountID, groupimagesizeaccount.FieldPriority:
			values[i] = new(sql.NullInt64)
		case groupimagesizeaccount.FieldSizeTier:
			values[i] = new(sql.NullString)
		case groupimagesizeaccount.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the GroupImageSizeAccount fields.
func (_m *GroupImageSizeAccount) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case groupimagesizeaccount.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case groupimagesizeaccount.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case groupimagesizeaccount.FieldSizeTier:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field size_tier", values[i])
			} else if value.Valid {
				_m.SizeTier = value.String
			}
		case groupimagesizeaccount.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case groupimagesizeaccount.FieldPriority:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field priority", values[i])
			} else if value.Valid {
				_m.Priority = int(value.Int64)
			}
		case groupimagesizeaccount.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the GroupImageSizeAccount.
// This includes values selected through modifiers, order, etc.
func (_m *GroupImageSizeAccount) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAccount queries the "account" edge of the GroupImageSizeAccount entity.
func (_m *GroupImageSizeAccount) QueryAccount() *AccountQuery {
	return NewGroupImageSizeAccountClient(_m.config).QueryAccount(_m)
}

// QueryGroup queries the "group" edge of the GroupImageSizeAccount entity.
func (_m *GroupImageSizeAccount) QueryGroup() *GroupQuery {
	return NewGroupImageSizeAccountClient(_m.config).QueryGroup(_m)
}

// Update returns a builder for updating this GroupImageSizeAccount.
// Note that you need to call GroupImageSizeAccount.Unwrap() before calling this method if this GroupImageSizeAccount
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *GroupImageSizeAccount) Update() *GroupImageSizeAccountUpdateOne {
	return NewGroupImageSizeAccountClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the GroupImageSizeAccount entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *GroupImageSizeAccount) Unwrap() *GroupImageSizeAccount {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: GroupImageSizeAccount is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *GroupImageSizeAccount) String() string {
	var builder strings.Builder
	builder.WriteString("GroupImageSizeAccount(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("size_tier=")
	builder.WriteString(_m.SizeTier)
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("priority=")
	builder.WriteString(fmt.Sprintf("%v", _m.Priority))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// GroupImageSizeAccounts is a parsable slice of GroupImageSizeAccount.
type GroupImageSizeAccounts []*GroupImageSizeAccount
