// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/groupimagesizeaccount"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// GroupImageSizeAccountDelete is the builder for deleting a GroupImageSizeAccount entity.
type GroupImageSizeAccountDelete struct {
	config
	hooks    []Hook
	mutation *GroupImageSizeAccountMutation
}

// Where appends a list predicates to the GroupImageSizeAccountDelete builder.
func (_d *GroupImageSizeAccountDelete) Where(ps ...predicate.GroupImageSizeAccount) *GroupImageSizeAccountDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *GroupImageSizeAccountDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GroupImageSizeAccountDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *GroupImageSizeAccountDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(groupimagesizeaccount.Table, sqlgraph.NewFieldSpec(groupimagesizeaccount.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// GroupImageSizeAccountDeleteOne is the builder for deleting a single GroupImageSizeAccount entity.
type GroupImageSizeAccountDeleteOne struct {
	_d *GroupImageSizeAccountDelete
}

// Where appends a list predicates to the GroupImageSizeAccountDelete builder.
func (_d *GroupImageSizeAccountDeleteOne) Where(ps ...predicate.GroupImageSizeAccount) *GroupImageSizeAccountDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *GroupImageSizeAccountDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{groupimagesizeaccount.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GroupImageSizeAccountDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
